name: my_flutter_project
description: A new Flutter project using Firebase

version: 1.0.0+1

environment:
  sdk: '^3.2.0'  # Ensure that the Dart SDK is compatible with your project

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core for initializing Firebase
  firebase_core: ^3.8.1

  # Firebase Authentication (if you're using Firebase Auth)
  firebase_auth: ^5.3.4

  # Firebase Firestore (if you're using Firestore)
  cloud_firestore: ^5.0.0

  # Firebase Messaging (if you're using push notifications)
  firebase_messaging: ^15.1.6

  # Other Firebase packages you might need
  # For example, Firebase Storage or Firebase Analytics
  firebase_storage: ^12.3.7
  firebase_analytics: ^11.3.6

  # For generating Firebase options (firebase_options.dart)
  flutterfire_cli: ^1.0.0  # Example, replace with latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
